<?php

/**
 * AnimeDb package.
 *
 * @author    Peter Gribanov <info@peter-gribanov.ru>
 * @copyright Copyright (c) 2026, Peter Gribanov
 * @license   https://www.gnu.org/licenses/gpl-3.0.html GPL-3.0-or-later
 */

/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

declare(strict_types=1);

namespace App\Service\Schema;

/**
 * Builds the normalized `sqlite_master` snapshot that `app:schema:check` compares against the
 * committed golden file, and renders the difference between two snapshots.
 *
 * A snapshot is a sorted list of `<type>\t<name>\t<sql>` rows. The only normalization is
 * whitespace collapsing: `sqlite_master` stores DDL verbatim, including the author's line breaks,
 * and touching anything else (quotes, literals inside CHECK) risks merging distinct DDL.
 */
final class SchemaSnapshot
{
    /**
     * @param list<array{type: string, name: string, sql: string|null}> $masterRows
     *
     * @return list<string>
     */
    public static function fromMasterRows(array $masterRows): array
    {
        $rows = [];
        foreach ($masterRows as $row) {
            if ($row['sql'] === null || $row['name'] === 'sqlite_sequence') {
                continue;
            }
            // FTS5 shadow tables: DDL is generated by the module and depends on the libsqlite3
            // version. Filter by type AND name — FTS triggers share the `anime_fts_` prefix.
            if ($row['type'] === 'table' && str_starts_with($row['name'], 'anime_fts_')) {
                continue;
            }
            $rows[] = $row['type']."\t".$row['name']."\t".self::normalize($row['sql']);
        }
        sort($rows, \SORT_STRING);

        return $rows;
    }

    public static function normalize(string $sql): string
    {
        return trim((string) preg_replace('/\s+/u', ' ', $sql));
    }

    /**
     * @param list<string> $rows
     */
    public static function serialize(array $rows): string
    {
        return $rows === [] ? '' : implode("\n", $rows)."\n";
    }

    /**
     * @return list<string>
     */
    public static function parse(string $content): array
    {
        $lines = explode("\n", $content);
        if (end($lines) === '') {
            array_pop($lines);
        }

        return $lines;
    }

    /**
     * Diff lines: `< row` for rows present only in the golden file, `> row` for rows present only
     * in the actual snapshot.
     *
     * @param list<string> $golden
     * @param list<string> $actual
     *
     * @return list<string>
     */
    public static function diff(array $golden, array $actual): array
    {
        $diff = [];
        foreach (array_diff($golden, $actual) as $row) {
            $diff[] = '< '.$row;
        }
        foreach (array_diff($actual, $golden) as $row) {
            $diff[] = '> '.$row;
        }

        return $diff;
    }
}
