/**
 * AnimeDb package.
 *
 * @author    Peter Gribanov <info@peter-gribanov.ru>
 * @copyright Copyright (c) 2026, Peter Gribanov
 * @license   https://www.gnu.org/licenses/gpl-3.0.html GPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const PHP_INI_TEMPLATE = path.join(__dirname, '..', 'bin', 'php', 'php.ini.template');

// Directives ensurePhpIni() must guarantee are present in the generated php.ini — checked against
// an existing file (not just written once) so an ini generated by an older template still gets the
// directives a newer build needs, without touching the rest of a file users are meant to be able to
// edit by hand. Presence alone is enough here: unlike extension_dir, none of these depend on where
// the application is installed, and a value a user edited by hand is left as-is rather than reset.
const REQUIRED_INI_DIRECTIVES = [
    { pattern: /^\s*memory_limit\s*=\s*\S+\s*$/m, render: () => 'memory_limit = 256M' },
    { pattern: /^\s*extension\s*=\s*intl\s*$/m, render: () => 'extension=intl' },
    { pattern: /^\s*extension\s*=\s*zip\s*$/m, render: () => 'extension=zip' },
    { pattern: /^\s*extension\s*=\s*pdo_sqlite\s*$/m, render: () => 'extension=pdo_sqlite' },
    { pattern: /^\s*extension\s*=\s*openssl\s*$/m, render: () => 'extension=openssl' },
    { pattern: /^\s*extension\s*=\s*mbstring\s*$/m, render: () => 'extension=mbstring' },
    { pattern: /^\s*extension\s*=\s*gd\s*$/m, render: () => 'extension=gd' },
];

// extension_dir is an install path, so unlike REQUIRED_INI_DIRECTIVES its value — not just its
// presence — must be checked: a reinstall into a different directory leaves the old ini in place
// (AppData survives a reinstall) with a now-stale path.
const EXTENSION_DIR_PATTERN = /^\s*extension_dir\s*=\s*"([^"]*)"\s*$/m;

/**
 * Renders bin/php/php.ini.template with {{TIMEZONE}}/{{EXTENSION_DIR}} substituted.
 *
 * @param {object}  options
 * @param {string}  options.extensionDir  path to the directory with the PHP extension DLLs
 * @param {string}  [options.timezone]    defaults to the host's IANA timezone name — pass this
 *                                        explicitly for a reproducible result (e.g. in CI)
 * @returns {string}
 */
function renderPhpIni({ extensionDir, timezone }) {
    const template = fs.readFileSync(PHP_INI_TEMPLATE, 'utf8');
    const resolvedTimezone = timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone;

    return template
        .replace('{{TIMEZONE}}', resolvedTimezone)
        .replace('{{EXTENSION_DIR}}', extensionDir);
}

/**
 * Creates php.ini at iniPath from the template if it doesn't exist yet. If it already exists, the
 * file is left in place (a user may have edited it by hand) and only appendMissingIniDirectives()
 * runs against it, so the required extension directives and an up-to-date extension_dir are
 * guaranteed either way.
 *
 * @param {object}  options
 * @param {string}  options.iniPath      full path to the php.ini file to create/update
 * @param {string}  options.iniDir       directory containing iniPath, created if missing
 * @param {string}  options.extensionDir path to the directory with the PHP extension DLLs
 * @param {string}  [options.timezone]   see renderPhpIni()
 * @returns {string} iniPath
 */
function ensurePhpIni({ iniPath, iniDir, extensionDir, timezone }) {
    if (fs.existsSync(iniPath)) {
        appendMissingIniDirectives(iniPath, extensionDir);
        return iniPath;
    }

    const ini = renderPhpIni({ extensionDir, timezone });

    fs.mkdirSync(iniDir, { recursive: true });
    fs.writeFileSync(iniPath, ini, 'utf8');
    return iniPath;
}

/**
 * Дописывает в конец существующего php.ini директивы из REQUIRED_INI_DIRECTIVES, которых в
 * нём ещё нет, и приводит extension_dir к актуальному пути. Для memory_limit и extension=
 * достаточно факта присутствия строки — она не зависит от каталога установки, а значение,
 * изменённое пользователем вручную, трогать нельзя. Для extension_dir этого мало: если
 * строка уже есть, но с другим путём (переустановка в другой каталог — AppData её переживает),
 * значение переписывается на месте, а не оставляется как дубль. Ничего не делает, если файл уже
 * актуален.
 *
 * @param {string} iniPath
 * @param {string} extensionDir
 */
function appendMissingIniDirectives(iniPath, extensionDir) {
    let content = fs.readFileSync(iniPath, 'utf8');
    let changed = false;

    const extensionDirMatch = content.match(EXTENSION_DIR_PATTERN);
    if (extensionDirMatch && extensionDirMatch[1] !== extensionDir) {
        content = content.replace(EXTENSION_DIR_PATTERN, `extension_dir = "${extensionDir}"`);
        changed = true;
    }

    const missingLines = REQUIRED_INI_DIRECTIVES
        .filter(({ pattern }) => !pattern.test(content))
        .map(({ render }) => render());

    if (!extensionDirMatch) {
        missingLines.unshift(`extension_dir = "${extensionDir}"`);
    }

    if (missingLines.length > 0) {
        content += `\n; Added by anime-db-desktop after an application upgrade\n${missingLines.join('\n')}\n`;
        changed = true;
    }

    if (changed) {
        fs.writeFileSync(iniPath, content, 'utf8');
    }
}

module.exports = { PHP_INI_TEMPLATE, renderPhpIni, ensurePhpIni };
